name: mercado_livre_app
description: "Desafio Fase 3 - App Mercado Livre"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/